apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: ismapolis
  annotations:
    argocd-image-updater.argoproj.io/image-list: blog=docker.io/ismapolis/polis-blog
    argocd-image-updater.argoproj.io/blog.update-strategy: latest
    argocd-image-updater.argoproj.io/blog.allow-tags: regexp:^[a-f0-9]{7}$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        # Contenedor principal: Nginx sirve los HTML
        - name: blog
          image: ismapolis/polis-blog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
