apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: ismapolis
  annotations:
    # Lista de contenedores que Image Updater debe observar
    argocd-image-updater.argoproj.io/image-list: blog=docker.io/ismapolis/polis-blog
    # Estrategia de actualización de la imagen
    argocd-image-updater.argoproj.io/blog.update-strategy: newest_build
    # Permitir solo tags que sean un hash de Git corto
    argocd-image-updater.argoproj.io/blog.allow-tags: "regexp:^[a-f0-9]{7}$"
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: docker.io/ismapolis/polis-blog:f38ce9e
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
