apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: ismapolis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        # Contenedor principal: servidor Astro
        - name: blog
          image: ismapolis/polis-blog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4321
          env:
            - name: NODE_ENV
              value: "production"
          volumeMounts:
            - name: content
              mountPath: /app/src/content
          readinessProbe:
            httpGet: { path: "/", port: 4321 }
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 4321 }
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5

        # Sidecar: reconstruye ficheros estáticos automáticamente
        - name: blog-builder
          image: ismapolis/polis-blog:latest
          command: ["sh", "-c"]
          args:
            - |
              while true; do
                inotifywait -e create,modify,delete -r /app/src/content/
                echo "Detected change, rebuilding..."
                npm run build
              done
          volumeMounts:
            - name: content
              mountPath: /app/content

      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: blog-content-pvc
