apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: ismapolis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 911 # asegura que todos los archivos del PVC sean accesibles
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          securityContext:
            runAsUser: 911 # usuario 'abc' dentro del contenedor
            runAsGroup: 911 # grupo 'abc'
          ports:
            - containerPort: 7878
              name: web
          volumeMounts:
            - name: media
              mountPath: /media
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: pvc-jellyfin
