apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: ismapolis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 911 # asegura que todos los archivos creados en los volúmenes sean accesibles
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          securityContext:
            runAsUser: 911
            runAsGroup: 911
          ports:
            - containerPort: 7878
              name: web
          volumeMounts:
            - name: media
              mountPath: /media
            - name: config
              mountPath: /config
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: pvc-jellyfin
        - name: config
          persistentVolumeClaim:
            claimName: pvc-radarr-config
