apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-external
    server: 192.168.1.130

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-radarr-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.130
    path: /mnt/nfs-external/radarr-config
