apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-jellyfin
    server: 192.168.1.141
