apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs-external
    server: 192.168.1.130
