apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin
  namespace: ismapolis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Gi
  volumeName: pv-jellyfin
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-config
  namespace: ismapolis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
