apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: ismapolis
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
      nodePort: 30096
  type: NodePort
