apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: ismapolis
spec:
  replicas: 1
  selector:
    matchLabels: { app: blog }
  template:
    metadata:
      labels: { app: blog }
    spec:
      containers:
        - name: blog
          # Reemplaza por tu imagen de Astro en producción
          image: ismapolis/polis-blog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4321 # o el puerto que exponga tu server Astro
          env:
            - name: NODE_ENV
              value: "production"
          volumeMounts:
            - name: content
              mountPath: /app/content/posts
              subPath: posts
            - name: content
              mountPath: /app/content/finds
              subPath: finds
          readinessProbe:
            httpGet: { path: "/", port: 4321 }
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 4321 }
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: blog-content-pvc
