name: Update Blog Image

on:
  repository_dispatch:
    types: [update-blog-image]

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update deployment manifest
        run: |
          echo "Imagen recibida: ${{ github.event.client_payload.image }}"
          sed -i "s|docker.io/ismapolis/polis-blog:.*|${{ github.event.client_payload.image }}|g" apps/blog/deployment.yaml

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add apps/blog/deployment.yaml
          if ! git diff --cached --quiet; then
            git commit -m "Update blog image"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ismapolis/cluster-deployment.git
            git push origin HEAD
          else
            echo "No hay cambios que commitear"
          fi
