name: Update Blog Image

on:
  repository_dispatch:
    types: [update-blog-image]

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update deployment manifest
        run: |
          echo "Imagen recibida: ${{ github.event.client_payload.image }}"
          sed -i "s|docker.io/ismapolis/polis-blog:.*|${{ github.event.client_payload.image }}|g" app/blog/blog-deployment.yaml

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/blog-deployment.yaml
          git diff --quiet || git commit -m "Update blog image" && git push
