apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
spec:
  project: default # o un proyecto personalizado si lo prefieres
  source:
    repoURL: "git@github.com:ismapolis/cluster-deployment.git" # SSH URL de tu repo privado
    targetRevision: main
    path: apps/blog
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ismapolis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
