apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:ismapolis/cluster-deployment.git"
    targetRevision: main
    path: apps/jellyfin
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
